hw4
Trage111/TheVeryFirst-Veronika pull request #5
Opened 2017-09-10 19:57 UTC by Trage111

2017-09-11 12:19 UTC, sinyakov requested changes

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +	node **array = new node*[counter];
Зачем тут нужны массивы?
Мы же разобрали рекурсивный способ.

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +		cout << i+1 << ": x = " << array[i]->data->x << "; y = " << array[i]->data->y << endl;
Вывод отдельной точки можно сделать отдельной функцией вне класса.
Во-первых, этот код повторяется уже второй раз.
Во-вторых, мы потом сделаем наш класс универсальным и тут будет вызываться функция вывода любого объекта.

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +		if (member == 0) {
Вы нумеруете элементы с 1?
Давайте сделаем нумерацию с 0, тогда будет проще.

Но даже если мы начинаем с 1, в чем особенность нуля?
Стоит тогда проверять и отрицательный аргумент.

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +	if (empty()) {
Чтобы не было вложенности ифов, можно сделать  так:
```
if (empty()) {
  cout << "Error in List::remove. List is empty" << endl;
  return void;
 } 
```
 Дальше сразу тот код, который в элсе.

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +				while(counter < member-1) {
Я бы шел до нужного элемента фором. До того момента, как нашли элемент.
На случай если не нашли, то после фора можно проверить, не в конце ли мы (tmp == nullptr).

2017-09-11 12:19 UTC, sinyakov commented on 17.class.cpp
> +		for (int count = 0; count < size(); count++) {
И вы каждый раз запускаете функцию сайз, которая идет по всему списку (O(n)).
Итого O(n^3). Так что хотя бы сайз нужно посчитать один раз и записать в переменную.

Но я предлагаю вообще не так делать.
Смысл листа именно в том, что мы не знаем размер!

Для массива мы делали так:

```
for (int i = 0; i < size; i++) {
  for (int j = i; j < size; j++) {
    ...
  }
}
```

Попробуйте для списка делать так:
```
for (node* i = 0; i != nullptr; i = i->next) {
  for (node* j = i; j != nullptr; j = j->next) {
    ...
  }
}
```

Плюс давайте функцию сравнения (comporator) вынесем в отельную функцию вне класса. В нее мы будем передавать i->data и j->data.

И сейчас у вас эта функция сортирует только по первому аргументу. Если первые равны, то вторые могут идти в неправильном порядке. В отдельной функции будет проще написать эту логику.

2017-09-11 15:39 UTC, Trage111 commented on 17.class.cpp
> +	node **array = new node*[counter];
Я, во-первых, не понимаю, почему рекурсивный способ лучше массивов. Мне кажется, что массивы лучше, так как памяти расходуется меньше.
Во-вторых, функция же должна что-то принимать, чтобы её можно было сделать рекурсивной?

2017-09-11 15:39 UTC, Trage111 commented on 17.class.cpp
> +		if (member == 0) {
Стоит тогда проверять и отрицательный аргумент. > Я её сделала принимающей unsigned int.

2017-09-11 15:51 UTC, sinyakov commented on 17.class.cpp
> +	node **array = new node*[counter];
Дело не в памяти. Все равно обычно используют двусвязные списки.

Вообще, рекурсия — это когда мы в функции вызываем саму себя. Больше никаких ограничений.

Но тут, правильно, нам нужно условие для выхода. Можно написать private метод, принимающий node*, и вызывать его в принтреверс.

2017-09-12 19:27 UTC, Trage111 commented on 17.class.cpp
> +		for (int count = 0; count < size(); count++) {
Попробуйте для списка делать так >> Не знаю, как это адекватно сделать, так как в отличие от массива тут надо следить за тремя элементами.
Если просто заменить каунтер на node* n = root; n != nullptr; n = n->next, функция работает неправильно, видимо, потому что root меняется.

2017-09-12 20:13 UTC, closed without merging